name: get and encrypt from private repo
on:
  pull_request:
  workflow_dispatch:
jobs:
  get-and-encrypt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: cawfeecake/secret-texts
        ssh-key: ${{ secrets.SSH_KEY_SECRET_TEXTS }}
    - run:
        ls -al
