name: Get and encrypt
on:
  workflow_dispatch:
jobs:
  get-and-encrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Get secrets repo
        uses: actions/checkout@v3
        with:
          repository: cawfeecake/secret-texts
          token: ${{ secrets.PERSONAL_PAT }}
      - name: Encrypt secret
        run:
          ENCRYPTED=$(gpg --batch --output secret.txt.gpg --passphrase password --symmetric secret.txt)
          echo "$ENCRYPTED"
